/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package accsettings;


import authentication.login;
import static authentication.register.eml;
import static authentication.register.usrname;
import config.Session;
import config.dbConnectors;
import config.passwordHasher;

import java.security.NoSuchAlgorithmException;

import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;



/**
 *
 * @author acer
 */
public class editpass extends javax.swing.JInternalFrame {

    /**
     * Creates new form adduser
     */
    public editpass() {
        initComponents();
         this.setBorder(javax.swing. BorderFactory.createEmptyBorder(0,0,0,0)); 
       BasicInternalFrameUI bi = (BasicInternalFrameUI) this.getUI();
       bi.setNorthPane (null);
    }
    
    
     
    
     
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        id = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        add = new javax.swing.JButton();
        CLEAR = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        conpassword = new javax.swing.JPasswordField();
        showpass = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        oldpass = new javax.swing.JPasswordField();

        setBackground(new java.awt.Color(255, 252, 239));
        setBorder(null);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 252, 239));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 252, 239));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        id.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        id.setEnabled(false);
        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });
        jPanel2.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 190, 30));

        jLabel2.setText("User ID:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, 20));

        add.setBackground(new java.awt.Color(255, 255, 255));
        add.setText("SAVE");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanel2.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 370, 130, -1));

        CLEAR.setBackground(new java.awt.Color(255, 255, 255));
        CLEAR.setText("CLEAR");
        CLEAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLEARActionPerformed(evt);
            }
        });
        jPanel2.add(CLEAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 130, -1));

        jLabel7.setText("Confirm password:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, -1, 20));

        conpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conpasswordActionPerformed(evt);
            }
        });
        jPanel2.add(conpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 260, 30));

        showpass.setBackground(new java.awt.Color(255, 255, 255));
        showpass.setText("View password");
        showpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showpassActionPerformed(evt);
            }
        });
        jPanel2.add(showpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 250, 20));

        jLabel8.setText("New password:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, 20));

        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        jPanel2.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 260, 30));

        jLabel9.setText("Old password:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, 20));

        oldpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oldpassActionPerformed(evt);
            }
        });
        jPanel2.add(oldpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 260, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 680, 420));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
         
        dbConnectors dbc = new dbConnectors();
         
         try{
        Session sess = Session.getInstance();
        String pass,oldpasswrd ,passs;
         passs= sess.getPassword();
         pass = passwordHasher.hashPassword(password.getText());       
         oldpasswrd = passwordHasher.hashPassword(oldpass.getText()); 
       if(!(passs.equals(oldpasswrd))){
        JOptionPane.showMessageDialog(null, "Wrong password");
       }
        else if(!(password.getText().equals(conpassword.getText()))){
      JOptionPane.showMessageDialog(null, "password not match");
     }  else{
             
             
            dbc.insertData("UPDATE tbl_users SET u_password ='"+pass+"' WHERE u_id ='"+id.getText()+"'");
            JOptionPane.showMessageDialog(null,"password updated successfully.");
             

        }       
       }catch(NoSuchAlgorithmException ex){
                    System.out.println(""+ex);}
    }//GEN-LAST:event_addActionPerformed

    private void CLEARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLEARActionPerformed
       
    }//GEN-LAST:event_CLEARActionPerformed

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
         Session sess = Session.getInstance();      
            oldpass.setEchoChar('*');
            password.setEchoChar('*');
            conpassword.setEchoChar('*');
        if(sess.getUid()== 0){
            JOptionPane.showMessageDialog(null, "No Account!, Please login first!");
            login lf = new login();
            lf.setVisible(true);
            this.dispose();
        }else{
                    id.setText(""+sess.getUid());
                    
        } 
    }//GEN-LAST:event_formInternalFrameActivated

    private void conpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_conpasswordActionPerformed

    private void showpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showpassActionPerformed
        if(showpass.isSelected()){
            oldpass.setEchoChar((char)0);
            password.setEchoChar((char)0);
            conpassword.setEchoChar((char)0);
        }  else {
            oldpass.setEchoChar('*');
            password.setEchoChar('*');
            conpassword.setEchoChar('*');
        }
    }//GEN-LAST:event_showpassActionPerformed

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    private void oldpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oldpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oldpassActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CLEAR;
    public javax.swing.JButton add;
    private javax.swing.JPasswordField conpassword;
    public javax.swing.JTextField id;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField oldpass;
    private javax.swing.JPasswordField password;
    private javax.swing.JCheckBox showpass;
    // End of variables declaration//GEN-END:variables
}
